import { StyleSheet } from 'react-native';
import { C } from '../constants/Colors';

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.white },
  flex: { flex: 1 },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 0.5,
    borderTopColor: C.border,
    backgroundColor: C.white,
  },
  tabItem: { alignItems: 'center', gap: 2 },
  tabIcon: { fontSize: 16 },
  tabLabel: { fontSize: 10, color: C.gray, fontWeight: '600' },
  tabLabelActive: { color: C.green },
  homeHeader: { alignItems: 'center', paddingHorizontal: 16, paddingTop: 14, paddingBottom: 6 },
  locationRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 3 },
  locationText: { fontSize: 13, fontWeight: '600', color: '#4C4C4C' },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bg,
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 13, color: C.text },
  searchPlaceholder: { fontSize: 13, color: C.gray },
  banner: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    overflow: 'hidden',
    height: 90,
    backgroundColor: '#D4EFC3',
  },
  bannerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: '100%',
  },
  bannerSmall: { fontSize: 10, color: C.gray },
  bannerTitle: { fontSize: 18, fontWeight: '800', color: C.text, lineHeight: 22 },
  bannerTag: { fontSize: 10, color: C.green, fontWeight: '700', marginTop: 3 },
  dots: { flexDirection: 'row', justifyContent: 'center', gap: 5, marginBottom: 10 },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.border },
  dotActive: { width: 18, backgroundColor: C.green, borderRadius: 4 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: C.text },
  seeAll: { fontSize: 12, color: C.green, fontWeight: '700' },
  hScrollContent: { paddingHorizontal: 16, paddingBottom: 16, gap: 12 },
  prodCard: {
    width: 110,
    backgroundColor: C.white,
    borderWidth: 0.5,
    borderColor: C.border,
    borderRadius: 14,
    padding: 10,
  },
  prodEmoji: { fontSize: 36, textAlign: 'center', marginBottom: 8 },
  prodName: { fontSize: 12, fontWeight: '700', color: C.text, marginBottom: 2 },
  prodUnit: { fontSize: 10, color: C.gray, marginBottom: 8 },
  prodRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  prodPrice: { fontSize: 13, fontWeight: '800', color: C.text },
  addBtn: {
    width: 26,
    height: 26,
    backgroundColor: C.green,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { color: C.white, fontSize: 18, lineHeight: 22, fontWeight: '600' },
  grocPill: {
    height: 64,
    minWidth: 140,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  grocPillLabel: { fontSize: 13, fontWeight: '700', color: '#3E423F' },
  grocGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  grocCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: C.white,
    borderWidth: 0.5,
    borderColor: C.border,
    borderRadius: 14,
    padding: 10,
  },
  grocCardEmoji: { fontSize: 32, textAlign: 'center', marginBottom: 8 },
  pdTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  pdBtn: { padding: 6 },
  pdBtnText: { fontSize: 22, color: C.text },
  pdImage: { alignItems: 'center', paddingVertical: 10 },
  pdBody: { paddingHorizontal: 16 },
  pdTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  pdName: { fontSize: 20, fontWeight: '800', color: C.text, lineHeight: 25 },
  pdUnit: { fontSize: 11, color: C.gray, marginTop: 3 },
  pdQtyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  qtyCtrl: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  qtyBtn: {
    width: 32,
    height: 32,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyBtnText: { fontSize: 18, color: C.text },
  qtyNum: { fontSize: 18, fontWeight: '700', color: C.text, minWidth: 24, textAlign: 'center' },
  pdPrice: { fontSize: 24, fontWeight: '800', color: C.text },
  starsRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  reviewCount: { fontSize: 11, color: C.gray, marginLeft: 5 },
  accordion: { borderTopWidth: 0.5, borderTopColor: C.border, paddingVertical: 12 },
  accHeader: { flexDirection: 'row', alignItems: 'center' },
  accTitle: { fontSize: 14, fontWeight: '700', color: C.text, flex: 1 },
  accArrow: { fontSize: 14, color: C.gray },
  accBadge: {
    backgroundColor: C.bg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginRight: 8,
  },
  accBadgeText: { fontSize: 10, color: C.gray },
  accBody: { fontSize: 12, color: C.gray, lineHeight: 19, marginTop: 8 },
  nutrRow: { flexDirection: 'row', gap: 20, marginTop: 10, flexWrap: 'wrap' },
  nutrItem: { alignItems: 'center' },
  nutrVal: { fontSize: 14, fontWeight: '700', color: C.text },
  nutrLbl: { fontSize: 10, color: C.gray },
  pdFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 0.5,
    borderTopColor: C.border,
    backgroundColor: C.white,
  },
  greenBtn: {
    backgroundColor: C.green,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  greenBtnText: { color: C.white, fontSize: 15, fontWeight: '700' },
  expHeader: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, alignItems: 'center' },
  expTitle: { fontSize: 18, fontWeight: '800', color: C.text },
  catGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 8,
  },
  catCard: {
    width: '47%',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 90,
    borderWidth: 0.5,
    borderColor: C.border,
  },
  catEmoji: { fontSize: 36, marginBottom: 8 },
  catName: { fontSize: 12, fontWeight: '700', color: C.text, textAlign: 'center', lineHeight: 17 },
  bevHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bevTitle: { fontSize: 16, fontWeight: '800', color: C.text },
  bevList: { paddingHorizontal: 16, paddingTop: 4 },
  bevRow: { gap: 12, marginBottom: 12 },
  bevCard: {
    flex: 1,
    backgroundColor: C.white,
    borderWidth: 0.5,
    borderColor: C.border,
    borderRadius: 14,
    padding: 10,
  },
  bevEmoji: { fontSize: 32, textAlign: 'center', marginBottom: 8 },
});